name: 📚 Generate Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create documentation
        shell: pwsh
        run: |
          # Create docs directory
          New-Item -ItemType Directory -Path "./docs" -Force | Out-Null

          $css = '* { margin: 0; padding: 0; box-sizing: border-box; } body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; color: #333; background: #f8f9fa; } .container { max-width: 1000px; margin: 0 auto; padding: 2rem; background: white; min-height: 100vh; } header { text-align: center; margin-bottom: 3rem; padding: 2rem 0; border-bottom: 1px solid #e9ecef; } h1 { font-size: 2.5rem; color: #2c3e50; margin-bottom: 0.5rem; } .subtitle { font-size: 1.1rem; color: #6c757d; } h2 { font-size: 1.8rem; color: #2c3e50; margin: 2rem 0 1rem 0; border-bottom: 2px solid #3498db; padding-bottom: 0.5rem; } h3 { font-size: 1.3rem; color: #34495e; margin: 1.5rem 0 0.5rem 0; } p { margin-bottom: 1rem; color: #555; } .nav { display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; } .nav a { background: #3498db; color: white; padding: 0.5rem 1rem; border-radius: 4px; text-decoration: none; transition: background 0.3s; } .nav a:hover { background: #2980b9; } .script-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 2rem; margin: 2rem 0; } .script-card { background: white; border: 1px solid #dee2e6; border-radius: 8px; padding: 1.5rem; box-shadow: 0 2px 4px rgba(0,0,0,0.1); transition: transform 0.2s, box-shadow 0.2s; } .script-card:hover { transform: translateY(-2px); box-shadow: 0 4px 8px rgba(0,0,0,0.15); } .script-title { font-size: 1.2rem; font-weight: 600; color: #2c3e50; margin-bottom: 0.5rem; } .script-description { color: #6c757d; margin-bottom: 1rem; } .script-link { background: #28a745; color: white; padding: 0.5rem 1rem; border-radius: 4px; text-decoration: none; display: inline-block; transition: background 0.3s; } .script-link:hover { background: #218838; } pre { background: #f8f9fa; border: 1px solid #e9ecef; border-radius: 4px; padding: 1rem; overflow-x: auto; margin: 1rem 0; } code { background: #f8f9fa; padding: 0.2rem 0.4rem; border-radius: 3px; font-family: "Consolas", "Monaco", monospace; } .feature-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1rem; margin: 1.5rem 0; } .feature { padding: 1rem; background: #f8f9fa; border-radius: 6px; border-left: 4px solid #3498db; } .feature strong { color: #2c3e50; } footer { margin-top: 3rem; padding-top: 2rem; border-top: 1px solid #e9ecef; text-align: center; color: #6c757d; } @media (max-width: 768px) { .container { padding: 1rem; } h1 { font-size: 2rem; } .nav { justify-content: center; } }'
          Set-Content -Path ./docs/style.css -Value $css

          # Extract script information
          function Get-ScriptInfo {
              param($ScriptPath)
              
              $content = Get-Content $ScriptPath -Raw
              $info = @{}
              
              # Extract synopsis
              if ($content -match '\.SYNOPSIS\s*([\s\S]*?)\.DESCRIPTION') {
                  $info.Synopsis = $matches[1].Trim()
              }
              
              # Extract description
              if ($content -match '\.DESCRIPTION\s*([\s\S]*?)\.PARAMETER') {
                  $info.Description = $matches[1].Trim()
              }
              
              # Extract parameters
              $paramMatches = [regex]::Matches($content, '\.PARAMETER\s+(\w+)\s*([\s\S]*?)(?=\.PARAMETER|\.EXAMPLE|\.INPUTS|\.OUTPUTS|\.NOTES|#>)')
              $info.Parameters = @()
              foreach ($match in $paramMatches) {
                  $info.Parameters += @{
                      Name = $match.Groups[1].Value
                      Description = $match.Groups[2].Value.Trim()
                  }
              }
              
              # Extract examples
              $exampleMatches = [regex]::Matches($content, '\.EXAMPLE\s*([\s\S]*?)(?=\.EXAMPLE|\.INPUTS|\.OUTPUTS|\.NOTES|#>)')
              $info.Examples = @()
              foreach ($match in $exampleMatches) {
                  $info.Examples += $match.Groups[1].Value.Trim()
              }
              
              return $info
          }

          # Generate script documentation
          $scripts = @(
              @{Name = "Convert-VideoToHEVC"; Path = "./Convert-VideoToHEVC.ps1"; Description = "Main HEVC conversion script with batch processing and quality presets"}
              @{Name = "Analyze-Compression"; Path = "./Analyze-Compression.ps1"; Description = "Analyzes compression efficiency and quality metrics"}
              @{Name = "Optimize-HEVCSettings"; Path = "./Optimize-HEVCSettings.ps1"; Description = "Finds optimal encoding settings for your content"}
              @{Name = "Verify-HEVCConversions"; Path = "./Verify-HEVCConversions.ps1"; Description = "Validates conversion integrity and quality"}
          )

          foreach ($script in $scripts) {
              if (Test-Path $script.Path) {
                  $info = Get-ScriptInfo $script.Path
                  
                  $html = "<!DOCTYPE html><html lang=`"en`"><head><meta charset=`"UTF-8`"><meta name=`"viewport`" content=`"width=device-width, initial-scale=1.0`"><title>$($script.Name) - PowerShell HEVC Converter</title><link rel=`"stylesheet`" href=`"./style.css`"></head><body><div class=`"container`"><header><h1>$($script.Name)</h1><p class=`"subtitle`">PowerShell HEVC Video Converter</p></header><div class=`"nav`"><a href=`"./index.html`">Home</a><a href=`"https://github.com/itsFelixH/powershell-hevc-converter`">GitHub</a><a href=`"https://github.com/itsFelixH/powershell-hevc-converter/issues`">Issues</a></div><h2>Overview</h2><p>$($script.Description)</p>$(if ($info.Synopsis) { "<h2>Synopsis</h2><p>$($info.Synopsis)</p>" })$(if ($info.Description) { "<h2>Description</h2><p>$($info.Description -replace '\n', '<br>')</p>" })$(if ($info.Parameters.Count -gt 0) { $paramHtml = "<h2>Parameters</h2>"; foreach ($param in $info.Parameters) { $paramHtml += "<h3>-$($param.Name)</h3><p>$($param.Description -replace '\n', '<br>')</p>" }; $paramHtml })$(if ($info.Examples.Count -gt 0) { $exampleHtml = "<h2>Examples</h2>"; for ($i = 0; $i -lt $info.Examples.Count; $i++) { $exampleHtml += "<h3>Example $($i + 1)</h3><pre><code>$($info.Examples[$i])</code></pre>" }; $exampleHtml })<footer><p>Documentation generated on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</p></footer></div></body></html>"
                  
                  Set-Content -Path "./docs/$($script.Name).html" -Value $html
              }
          }

          # Generate index page
          $indexHtml = "<!DOCTYPE html><html lang=`"en`"><head><meta charset=`"UTF-8`"><meta name=`"viewport`" content=`"width=device-width, initial-scale=1.0`"><title>PowerShell HEVC Converter</title><link rel=`"stylesheet`" href=`"./style.css`"></head><body><div class=`"container`"><header><h1>PowerShell HEVC Converter</h1><p class=`"subtitle`">Simple and efficient video conversion toolkit</p></header><div class=`"nav`"><a href=`"https://github.com/itsFelixH/powershell-hevc-converter`">GitHub Repository</a><a href=`"https://github.com/itsFelixH/powershell-hevc-converter/releases`">Download</a><a href=`"https://github.com/itsFelixH/powershell-hevc-converter/issues`">Report Issues</a></div><h2>About</h2><p>A collection of PowerShell scripts for converting videos to HEVC (H.265) format using FFmpeg. Features batch processing, quality presets, and comprehensive analysis tools.</p><div class=`"feature-grid`"><div class=`"feature`"><strong>Batch Processing</strong><br>Convert multiple files automatically with progress tracking</div><div class=`"feature`"><strong>Quality Presets</strong><br>Optimized settings for different content types</div><div class=`"feature`"><strong>Hardware Acceleration</strong><br>Support for NVENC, QSV, and other hardware encoders</div><div class=`"feature`"><strong>Quality Analysis</strong><br>VMAF, PSNR, and SSIM metrics for quality validation</div></div><h2>Main Script: Convert-VideoToHEVC</h2><p>The primary conversion script that handles the heavy lifting. It converts various video formats to HEVC with intelligent defaults and customizable settings.</p><h3>Quick Start</h3><pre><code># Convert all videos in current directory`n.\Convert-VideoToHEVC.ps1`n`n# Convert with custom quality`n.\Convert-VideoToHEVC.ps1 -crf 20 -preset slow`n`n# Use a preset profile`n.\Convert-VideoToHEVC.ps1 -Profile Animation</code></pre><h3>Key Features</h3><ul><li>Supports MKV, MP4, MOV, WMV, AVI, FLV, M4V formats</li><li>10 preset profiles for different content types</li><li>Batch processing with pause/resume capability</li><li>Automatic error handling and recovery</li><li>Detailed logging and progress tracking</li><li>Hardware acceleration detection</li></ul><h2>Available Scripts</h2><div class=`"script-grid`">"
          
          foreach ($script in $scripts) {
              if (Test-Path $script.Path) {
                  $indexHtml += "<div class=`"script-card`"><div class=`"script-title`">$($script.Name)</div><div class=`"script-description`">$($script.Description)</div><a href=`"./$($script.Name).html`" class=`"script-link`">View Documentation</a></div>"
              }
          }
          
          $indexHtml += "</div><h2>Requirements</h2><ul><li>PowerShell 5.1 or later</li><li>FFmpeg with libx265 support</li><li>Windows 10/11 (or PowerShell Core on other platforms)</li></ul><footer><p>Documentation generated on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</p></footer></div></body></html>"
          
          Set-Content -Path ./docs/index.html -Value $indexHtml

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
